SSID='ssid of twilio'
AUTH_TOKEN='auth token of twilio'
FROM_NUMBER='number auto generated by twilio'
TO_NUMBER='+91 your number'
API_KEY='api key of bolt cloud'
DEVICE_ID='bolt iot device id'
FRAME_SIZE= 10
MUL_FACTOR= 6
